name: IaC Multi Environment setup

on:
  push:
    branches:
      - dev

jobs:
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      TF_CLI_ARGS: "-input=false"

    steps:
	# Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

    # Example: AWS OIDC authentication
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ap-south-1
	# Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init
	# Create or Select work space dev environment
      - name: Select Workspace
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            terraform workspace select dev || terraform workspace new dev

      - name: Terraform Validate
        run: |
          terraform fmt -check
          terraform validate
	 # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            terraform plan -var-file=environments/dev/terraform.tfvars -out=plan.tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: plan.tfplan

      - name: Terraform Apply (Dev auto)
        if: github.ref_name == 'dev'
        run: terraform apply -auto-approve plan.tfplan
